f = open("/home/thomas/Documenti/GitHub/University/Python/Esami/Gestione_Supermercati/supermercati.txt", "r")
line = f.readline().strip()
print(line)
line2 = f.readline().strip()
word = line2.split()
print(line)
print(word)
print(line2)
f.close()