CREATE TABLE CLIENTE (
  ID_Cliente INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(50) NOT NULL,
  Cognome VARCHAR(50) NOT NULL,
  Eta INT NOT NULL CHECK (Eta >= 18),
  Email VARCHAR(100) NOT NULL UNIQUE,
  Telefono VARCHAR(20)
);

CREATE TABLE EVENTO (
  ID_Evento INT AUTO_INCREMENT PRIMARY KEY,
  NomeEvento VARCHAR(100) NOT NULL,
  Data DATE NOT NULL,
  Ora TIME NOT NULL,
  Descrizione TEXT,
  PrezzoBiglietto DECIMAL(6,2) NOT NULL,
  CapienzaMassima INT NOT NULL CHECK (CapienzaMassima > 0)
);

CREATE TABLE BIGLIETTO (
  ID_Biglietto INT AUTO_INCREMENT PRIMARY KEY,
  DataAcquisto DATE NOT NULL,
  PrezzoPagato DECIMAL(6,2) NOT NULL,
  ID_Cliente INT NOT NULL,
  ID_Evento INT NOT NULL,
  FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente) ON DELETE CASCADE,
  FOREIGN KEY (ID_Evento) REFERENCES EVENTO(ID_Evento) ON DELETE CASCADE
);
